version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    labels:
      - dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    labels:
      - docker-image
  - package-ecosystem: "helm"
    directory: "/helm"
    schedule:
      interval: daily
    labels:
      - helm