/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocaleAndTimeSettingsDTO } from './localeAndTimeSettingsDTO';
import { PrivacySettingsDTO } from './privacySettingsDTO';
import { PreferencesDTO } from './preferencesDTO';


export interface AccountSettingsDTO { 
    guid?: string;
    persisted?: boolean;
    version?: number;
    controlTraceabilityManual?: boolean;
    creationDate?: string;
    creationUser?: string;
    modificationDate?: string;
    modificationUser?: string;
    localeAndTimeSettings?: LocaleAndTimeSettingsDTO;
    notificationSettings?: object;
    preferences?: Array<PreferencesDTO>;
    privacySettings?: PrivacySettingsDTO;
}

