/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrivacySettingsDTOv1 } from './privacySettingsDTOv1';
import { PreferencesDTOv1 } from './preferencesDTOv1';
import { LocaleAndTimeSettingsDTOv1 } from './localeAndTimeSettingsDTOv1';


export interface AccountSettingsDTOv1 { 
    guid?: string;
    persisted?: boolean;
    version?: number;
    controlTraceabilityManual?: boolean;
    creationDate?: string;
    creationUser?: string;
    modificationDate?: string;
    modificationUser?: string;
    localeAndTimeSettings?: LocaleAndTimeSettingsDTOv1;
    notificationSettings?: object;
    preferences?: Array<PreferencesDTOv1>;
    privacySettings?: PrivacySettingsDTOv1;
}

