/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AvatarInfoDTOv1 } from './avatarInfoDTOv1';
import { UserPersonDTOv1 } from './userPersonDTOv1';
import { AccountSettingsDTOv1 } from './accountSettingsDTOv1';
import { MembershipDTO } from './membershipDTO';


export interface UserProfileDTOv1 {
    guid?: string;
    persisted?: boolean;
    version?: number;
    controlTraceabilityManual?: boolean;
    creationDate?: string;
    creationUser?: string;
    modificationDate?: string;
    modificationUser?: string;
    accountSettings?: AccountSettingsDTOv1;
    avatar?: AvatarInfoDTOv1;
    identityProvider?: string;
    identityProviderId?: string;
    memberships?: Array<MembershipDTO>;
    organization?: string;
    person?: UserPersonDTOv1;
    roles?: Array<string>;
    userId?: string;
}

