/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserPersonAddressDTO } from './userPersonAddressDTO';
import { UserPersonPhoneDTO } from './userPersonPhoneDTO';


export interface UserPersonDTO { 
    guid?: string;
    persisted?: boolean;
    version?: number;
    controlTraceabilityManual?: boolean;
    creationDate?: string;
    creationUser?: string;
    modificationDate?: string;
    modificationUser?: string;
    address?: UserPersonAddressDTO;
    displayName?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    phone?: UserPersonPhoneDTO;
}

