{{ if .Values.operator.apm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "common.names.fullname" . }}-apm-config"
  annotations:
    appId: {{ include "common.names.fullname" . }}
    filename: "permissions.csv"
  labels:
    app: {{ include "common.names.fullname" . }}
{{ include "angular.labels.common" $ | indent 4 }}
data:
{{ if .Values.operator.apm.content }}
  permissions.csv: |-
{{ $.Values.operator.apm.content | indent 4 }}
{{ end }}
{{ end }}
