{{- if .Values.routing.enabled }}
{{- if eq (include "angular.routing.type" $) "traefik" }}
{{- if .Values.routing.stripprefix }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "common.names.fullname" . }}-{{ .Release.Namespace }}-middleware
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.routing.path }}
{{ end }}
{{ end }}
{{ end }}
