apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    app: {{ include "common.names.fullname" . }}
{{ include "angular.labels.common" $ | indent 4 }}
spec:
  selector:
    app: {{ include "common.names.fullname" . }}
{{ include "angular.labels.common" $ | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.pod.port }}
