{{- if .Values.routing.enabled }}
{{- if eq (include "angular.routing.type" $) "traefik" }}
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: {{ include "common.names.fullname" . }}-{{ .Release.Namespace }}
  labels:
    app: {{ include "common.names.fullname" . }}
{{ include "angular.labels.common" $ | indent 4 }}  
spec:
  entryPoints:
    {{- range $ep := .Values.routing.entryPoints }}
    - {{ $ep }}
    {{ end }}
    {{- range $ep := .Values.global.routing.entryPoints }}
    - {{ $ep }}
    {{ end }}
  routes:
    - kind: Rule
      {{ if .Values.routing.backend }}
      match: Host(`{{ include "common.names.fullname" . }}-{{ .Release.Namespace }}.{{ .Values.global.default_url | default .Values.routing.default_url }}`){{ include "angular.traefik.path" $ }}
      {{ else if .Values.routing.hostName }}
      match: Host(`{{ .Values.routing.hostName }}`){{ include "angular.traefik.path" $ }}
      {{ else if .Values.global.hostName }}
      match: Host(`{{ .Values.global.hostName }}`){{ include "angular.traefik.path" $ }}
      {{ else  }}
      match: Host(`{{ include "common.names.fullname" . }}-{{ .Release.Namespace }}.{{ .Values.global.default_url | default .Values.routing.default_url }}`){{ include "angular.traefik.path" $ }}
      {{ end }}
      {{ if .Values.routing.stripprefix }}
      middlewares:
        - name: {{ include "common.names.fullname" . }}-{{ .Release.Namespace }}-middleware
      {{ end }}
      services:
        - kind: Service
          name: {{ include "common.names.fullname" . }}
          port: {{ .Values.service.port }}
{{ end }}
{{ end }}
