apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-apm-config"
  annotations:
    appId: {{ .Release.Name }}
    filename: "permissions.csv"
data:
  permissions.csv: |-
{{ $.Files.Get "permissions.csv" | indent 4 }}
