apiVersion: v2
name: ping-angular
version: 0.0.0
appVersion: 0.0.0
description: Onecx ping angular application
keywords:
  - angular
  - onecx
sources:
  - https://github.com/onecx/ping-angular
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts    
