apiVersion: v2
name: ${project.name}
version: ${project.version}
appVersion: ${project.version}
description: ${project.name}
keywords:
  - ${project.name}
sources:
  - https://gitlab.com/1000kit/apps/tkit-portal/${project.name}
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  # https://gitlab.com/1000kit/infra/helm/angular.git
  - name: angular
    version: ^0
    repository: alias:1000kit
    alias: app
