name: Build

on:
  push:
    branches:
      - main
jobs:
  angular:
    uses: onecx/ci-npm/.github/workflows/angular.yml@main
    secrets: inherit
  docker:
    uses: onecx/ci-common/.github/workflows/docker.yml@main
    needs: angular
    secrets: inherit
    with:
      samoDockerFile: Dockerfile
  helm:
    uses: onecx/ci-common/.github/workflows/helm.yml@main
    needs: docker
    secrets: inherit
    with:
      packageDir: '.'
      samoHelmSourceDir: helm
      samoHelmSourceCopy: 'true'

